# Project Name
TARGET = polymod

# Sources
CPP_SOURCES = polymod.cpp \
IO.cpp \
VCO.cpp \
VCF.cpp \
Connection.cpp \
Module.cpp \
Socket.cpp

# Library Locations
LIBDAISY_DIR = ../DaisyExamples/libDaisy/
DAISYSP_DIR = ../DaisyExamples/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
