# Project Name
TARGET = polymod

# Sources
CPP_SOURCES = polymod.cpp \
Connection.cpp \
IO.cpp \
Module.cpp \
Socket.cpp \
VCO.cpp \
VCF.cpp \
LFO.cpp \
Reverb.cpp \
BitCrusher.cpp \
VCA.cpp \
Envelope.cpp \
Mult.cpp \
Noise.cpp \
Mixer.cpp

# Library Locations
LIBDAISY_DIR = ../DaisyExamples/libDaisy/
DAISYSP_DIR = ../DaisyExamples/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
