# Project Name
TARGET = polymod

# Sources
CPP_SOURCES = polymod.cpp \
Connection.cpp \
Socket.cpp \
modules/Module.cpp \
modules/IO.cpp \
modules/VCO.cpp \
modules/VCF.cpp \
modules/LFO.cpp \
modules/Reverb.cpp \
modules/BitCrusher.cpp \
modules/VCA.cpp \
modules/Envelope.cpp \
modules/Mult.cpp \
modules/Noise.cpp \
modules/Mixer.cpp

# Library Locations
LIBDAISY_DIR = ../DaisyExamples/libDaisy/
DAISYSP_DIR = ../DaisyExamples/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
